version: "3.7"
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    environment:
      - JUPYTER_TOKEN=junot
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: datascience-notebook-container
